name: Build and Deploy LaTeX Document

on:
  push:
    branches:
      - main  # Change this if you're using a different branch for LaTeX source

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # This should be where the main.pdf is located after compilation
        publish_branch: gh-pages  # Deploy to the gh-pages branch
