name: Build and Deploy LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
    
    - name: Copy index.html to the build directory
      run: |
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Resume</title>
            <style>
                html, body {
                    height: 100%;
                    margin: 0;
                }
                body {
                    display: flex;
                    justify-content: center;
                    align-items: center;
                }
                embed {
                    width: 100%;
                    height: 100%;
                    border: none;
                }
            </style>
        </head>
        <body>
            <embed src="main.pdf" type="application/pdf">
        </body>
        </html>

    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Deploy everything in the root directory
        publish_branch: gh-pages
