name: Build and Deploy LaTeX Document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
    

    - name: Create index.html file
      run: |
        echo '<!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Resume</title>
            <style>
                html, body {
                    height: 100%;
                    margin: 0;
                    padding: 0;
                }
                #pdf-container {
                    position: absolute;
                    top: 0;
                    left: 0;
                    width: 100%;
                    height: 100%;
                    overflow: hidden;
                }
                iframe {
                    position: absolute;
                    top: 0;
                    left: 0;
                    width: 100%;
                    height: 100%;
                    border: none;
                }
                #download-button {
                    position: absolute;
                    top: 10px;
                    right: 10px;
                    background-color: #007bff;
                    color: white;
                    padding: 10px 20px;
                    border: none;
                    border-radius: 5px;
                    text-decoration: none;
                    font-size: 16px;
                    cursor: pointer;
                    z-index: 1000;
                }
                #download-button:hover {
                    background-color: #0056b3;
                }
            </style>
        </head>
        <body>
            <div id="pdf-container">
                <iframe src="main.pdf#toolbar=0" type="application/pdf"></iframe>
            </div>
            <a id="download-button" href="main.pdf" download="Resume.pdf">Download PDF</a>
        </body>
        </html>' > index.html
      
        
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  
        publish_branch: gh-pages
